
name: Runner

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "storage/**" ]
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-action.txt ]; then pip install -r requirements-action.txt; fi
    - name: Run
      env:
        data: ${{ secrets.data }}
      run: |
        curl -s ifconfig.me
        git status
        python runner.py
        
        git config --global user.name 'otto'
        git config --global user.email 'otto@users.noreply.github.com'
        git add storage
        git commit -am "Automated report" || true
        git push || true